project_id = "xhyzzwjjtlxhdhvauzjx"

[functions.prompt-playground]
verify_jwt = false

[functions.generate-prompt]
verify_jwt = false

[functions.execute-workflow-prompt]
verify_jwt = false

[functions.invite-user]
verify_jwt = false
